name: Build Docker Package

# Manually trigger
on:
  workflow_dispatch:
    inputs:
      docker_tags:
        description: Docker tags to publish with (comma seperated)
        required: true
        type: string
      build_type:
        description: Which build type
        default: update
        type: choice
        options: [ update, dev ]

jobs:
  build-docker-package:
    name: Build Docker Package
    runs-on: ubuntu-latest
    steps:
        - name: Pull code
          uses: actions/checkout@v3
          with:
            path: ab_platform_web
            submodules: true
            ref: ${{ inputs.ref }}

        - name: Pull ab_service_web
          uses: actions/checkout@v3
          with:
            path: web
            repository: digi-serve/ab_service_web
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Install dependencies
          run: npm install
          working-directory: ./ab_platform_web

        # Webpack
        - name: Webpack build
          run: npm run build:${{ inputs.build_type }}
          working-directory: ./ab_platform_web
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

        # Docker
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            build-args: BRANCH=${{ inputs.base_tag }}
            tags: digiserve/ab-web:${{ inputs.docker_tags }}
            context: ./web

