name: PR Merged
on:
  pull_request:
    types: [closed]
    branches: [master]
permissions:
  contents: write
jobs:
  call-get-label:
    name: Label
    # Only run if the PR closed by merging and we have a label
    if: ${{ github.event.pull_request.merged }}
    uses: CruGlobal/.github/.github/workflows/get-pr-release-label.yml@master
  call-e2e-tests:
    name: Test
    needs: [call-get-label]
    # Only run if the PR closed by merging and we have a label
    if: ${{ needs.call-get-label.outputs.valid == 'true' }}
    uses: ./.github/workflows/e2e-tests.yml
  call-bump-version:
    name: Version
    # Only run if tests pass 
    needs: [ call-get-label, call-e2e-tests ]
    uses: CruGlobal/.github/.github/workflows/bump-version.yml@master
    with:
      ref: ${{ github.ref }}
      type: ${{ needs.call-get-label.outputs.label }}
  call-create-release:
    name: Release
    uses: CruGlobal/.github/.github/workflows/create-release.yml@master
    needs: [call-bump-version]
    with:
      tag: v${{ needs.call-bump-version.outputs.new_version }}
  call-dispatch-web-update:
    needs: [ call-bump-version, call-get-label ]
    uses: CruGlobal/.github/.github/workflows/dispatch-update.yml@master
    with:
      dispatch_repos: '["ab_service_web"]'
      dispatch_type: "web_new_version"
      type: ${{ needs.call-get-label.outputs.label }}
      version: ${{ needs.call-bump-version.outputs.new_version }}
      app_id: ${{ vars.GS_DEV_APP_ID }}
    secrets:
      app_token: ${{ secrets.GS_DEV_APP_PK }}
